const cities = [
  "Alameda",
  "Albany",
  "Antioch",
  "Belmont",
  "Berkeley",
  "Brentwood",
  "Brisbane",
  "Burlingame",
  "Concord",
  "Cupertino",
  "Daly City",
  "Dublin",
  "Emeryville",
  "Foster City",
  "Fremont",
  "Half Moon Bay",
  "Hayward",
  "Lafayette",
  "Livermore",
  "Los Altos",
  "Martinez",
  "Menlo Park",
  "Millbrae",
  "Mountain View",
  "Napa",
  "Oakland",
  "Pacifica",
  "Pittsburg",
  "Pleasanton",
  "Redwood City",
  "San Francisco",
  "San Jose",
  "San Mateo",
  "San Ramon",
  "Sunnyvale",
  "Union City",
  "Walnut Creek"
]

export default cities;
